# Matriz - Lista de exercícios

### 1. Faça um programa que carregue uma matriz 2 x 2,  que representa o salário de 4 funcionários, calcule e mostre a soma total de todos os elementos que será o montante pago pela empresa a esses funcionários

In [0]:
#1. Faça um programa que carregue uma matriz 2 x 2, que representa o salário de 4 funcionários, calcule e mostre a soma total de todos os elementos que será o montante pago pela empresa a esses funcionários
import numpy as np
sal = np.empty([2,2])
soma = 0
for l in range(2):
  for c in range(2):
    sal[l,c] = float(input('Informe o salário do funcionário: R$'))
    soma += sal[l,c]
#fPag = np.sum(sal)
print('O montante total pago pela empresa foi R$ {:.2f}.' .format(soma))

Informe o salário do funcionário: R$1000
Informe o salário do funcionário: R$2000
Informe o salário do funcionário: R$4000
Informe o salário do funcionário: R$8000
O montante total pago pela empresa foi R$ 15000.00.


### 2. Faça um programa que carregue uma matriz 2 x 2, que representa preços de produtos, crie outra matriz que armazene todos os preços com 7% de aumento.


In [0]:
#2. Faça um programa que carregue uma matriz 2 x 2, que representa preços de produtos, crie outra matriz que armazene todos os preços com 7% de aumento.
import numpy as np
precos = np.empty([2,2])
pAum = np.empty([2,2])
for l in range(2):
  for c in range(2):
    precos[l,c] = float(input('Informe o preço do produto: R$'))
#pAum = precos*1.07
    pAum[l,c] = precos[l,c]*1.07
print('\nA matriz de preços é:',*precos)
print('A matriz de preços aumentados é:',*pAum)


Informe o preço do produto: R$1000
Informe o preço do produto: R$2000
Informe o preço do produto: R$4000
Informe o preço do produto: R$8000
A matriz de preços é: [1000. 2000.] [4000. 8000.]
A matriz de preços aumentados é: [1070. 2140.] [4280. 8560.]


###3. Faça um programa para armazenar em uma matriz 5x2 preços. Encontre e apresente as posições dos valores menores que 23 reais.

In [0]:
#3. Faça um programa para armazenar em uma matriz 5x2 preços. Encontre e apresente as posições dos valores menores que 23 reais.
import numpy as np
precos = np.empty([5,2])
for l in range(5):
  for c in range(2):
    precos[l,c] = float(input('Informe o preço do produto: R$'))
print()
for l in range(len(precos[:, 0])):
  for c in range(len(precos[0, :])):
    if precos[l,c] < 23:
      print('A posição do preço R${:.2f} é na linha {} e coluna {}.' .format(precos[l,c],l,c))

Informe o preço do produto: R$10
Informe o preço do produto: R$20
Informe o preço do produto: R$30
Informe o preço do produto: R$40
Informe o preço do produto: R$12
Informe o preço do produto: R$45
Informe o preço do produto: R$23
Informe o preço do produto: R$56
Informe o preço do produto: R$30
Informe o preço do produto: R$1

A posição do preço R$10.00 é na linha 0 e coluna 0.
A posição do preço R$20.00 é na linha 0 e coluna 1.
A posição do preço R$12.00 é na linha 2 e coluna 0.
A posição do preço R$1.00 é na linha 4 e coluna 1.


In [0]:
# ALTERNATIVO 3. Faça um programa para armazenar
import numpy as np
precos = np.array([[14, 25],[36, 12],[13, 21],[26, 28],[29, 30]])
for l in range(len(precos[:, 0])):
  for c in range(len(precos[0, :])):
    if precos[l,c] < 23:
      print('A posição do preço R${:.2f} é na linha {} e coluna {}.' .format(precos[l,c],l,c))

A posição do preço R$14.00 é na linha 0 e coluna 0.
A posição do preço R$12.00 é na linha 1 e coluna 1.
A posição do preço R$13.00 é na linha 2 e coluna 0.
A posição do preço R$21.00 é na linha 2 e coluna 1.


###4. Escreva um programa que leia inteiros positivos m e n e os elementos de uma matriz A de números inteiros de dimensão m x n e conta o número de elementos que são iguais a zero.

In [0]:
#4. Escreva um programa que leia inteiros positivos m e n e os elementos de uma matriz A de números inteiros de dimensão m x n e conta o número de elementos que são iguais a zero.
import numpy as np
cont0 = 0
lin = int(input('Informe o número de linhas da matriz: '))
col = int(input('Informe o número de colunas da matriz: '))
print()
matA = np.empty([lin,col])
for l in range(lin):
  for c in range(col):
    matA[l,c] = float(input('Informe um número inteiro positivo: '))
    if matA[l,c] == 0:
      cont0 += 1
print('\nA quantidade de elementos iguais a zero na matriz A é {}.' .format(cont0))

Informe o número de linhas da matriz: 3
Informe o número de colunas da matriz: 3

Informe um número inteiro positivo: 0
Informe um número inteiro positivo: 1
Informe um número inteiro positivo: 2
Informe um número inteiro positivo: 3
Informe um número inteiro positivo: 0
Informe um número inteiro positivo: 4
Informe um número inteiro positivo: 5
Informe um número inteiro positivo: 6
Informe um número inteiro positivo: 0

A quantidade de elementos iguais a zero na matriz A é 3.


###5. Elabore um programa que preencha uma matriz 6 4 com números inteiros, calcule e mostre quantos elementos dessa matriz são maiores que 30 e, em seguida, monte uma segunda matriz com os elementos diferentes de 30. No lugar do número 30, da segunda matriz, coloque o número zero.

In [0]:
# 5. Elabore um programa que
import numpy as np
mat = np.empty([6,4], dtype=int)
mat2 = np.empty([6,4], dtype=int)
cont30 = 0
for l in range(6):
  for c in range(4):
    mat[l,c] = int(input('Informe um número inteiro: '))
    if mat[l,c] > 30:
      cont30 +=1
      mat2[l,c] = mat[l,c]
    else:
      if mat[l,c] == 30:
        mat2[l,c] = 0
      else:
        mat2[l,c] = mat[l,c]
print('\nHá {} números maiores que trinta.' .format(cont30))
print('\n',mat2)
print('\n A matriz 1: ',mat2)

Informe um número inteiro: 14
Informe um número inteiro: 25
Informe um número inteiro: 36
Informe um número inteiro: 30
Informe um número inteiro: 74
Informe um número inteiro: 85
Informe um número inteiro: 10
Informe um número inteiro: 1
Informe um número inteiro: 2
Informe um número inteiro: 3
Informe um número inteiro: 4
Informe um número inteiro: 5
Informe um número inteiro: 6
Informe um número inteiro: 7
Informe um número inteiro: 8
Informe um número inteiro: 9
Informe um número inteiro: 10
Informe um número inteiro: 20
Informe um número inteiro: 30
Informe um número inteiro: 40
Informe um número inteiro: 50
Informe um número inteiro: 60
Informe um número inteiro: 70
Informe um número inteiro: 80

Há 8 números maiores que trinta.

 [[14 25 36  0]
 [74 85 10  1]
 [ 2  3  4  5]
 [ 6  7  8  9]
 [10 20  0 40]
 [50 60 70 80]]


In [0]:
mat

array([[14, 25, 36, 30],
       [74, 85, 10,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

###6. Criar uma matriz para os 6 módulos com 35 alunos que armazene as notas. Apresente o aluno de cada módulo e o do curso que possui maior nota, também apresente se existe algum aluno que possui nota igual a 2 identificando que número é o aluno (coluna) e qual módulo (linha).

In [0]:
#6. Criar uma matriz para os 6 módulos com 35 alunos
import numpy as np
notas = np.empty([3,4])
for l in range(3):
  maNS = -1
  for c in range(4):
    notas[l,c] = float(input('Informe a nota do {}º aluno do {}º módulo: ' .format(c+1,l+1)))
    if l == 0 and c == 0:
      maNC = notas[l,c]
      maNS = notas[l,c]
    else:
      if maNC < notas[l,c]:
        maNC = notas[l,c]
      if maNS < notas[l,c]:
        maNS = notas[l,c]
  print('\nA maior nota do {}º módulo é {}.' .format(l+1,maNS),end="\n\n")
print('A maior nota do curso é', maNC)
print('\nOs seguintes alunos tiraram nota 2:')
for l in range(3):
  for c in range(4):
    if notas[l,c] == 2:
      print('O aluno nº {} do {}º módulo.' .format(c+1,l+1))


Informe a nota do 1º aluno do 1º módulo: 9
Informe a nota do 2º aluno do 1º módulo: 8
Informe a nota do 3º aluno do 1º módulo: 7
Informe a nota do 4º aluno do 1º módulo: 6

A maior nota do 1º módulo é 9.0.

Informe a nota do 1º aluno do 2º módulo: 10
Informe a nota do 2º aluno do 2º módulo: 2
Informe a nota do 3º aluno do 2º módulo: 5
Informe a nota do 4º aluno do 2º módulo: 7

A maior nota do 2º módulo é 10.0.

Informe a nota do 1º aluno do 3º módulo: 5
Informe a nota do 2º aluno do 3º módulo: 6
Informe a nota do 3º aluno do 3º módulo: 4
Informe a nota do 4º aluno do 3º módulo: 2

A maior nota do 3º módulo é 6.0.

A maior nota do curso é 10.0

Os seguintes alunos tiraram nota 2:
O aluno nº 2 do 2º módulo.
O aluno nº 4 do 3º módulo.


In [0]:
#6. Criar uma matriz para os 6 módulos com 35 alunos
import numpy as np
notas = np.empty([6,35], dtype=float)
for l in range(6):
  maNS = -1
  for c in range(35):
    notas[l,c] = float(input('Informe a nota do {}º aluno do {}º módulo: ' .format(c+1,l+1)))
    if l == 0 and c == 0:
      maNC = notas[l,c]
      maNS = notas[l,c]
    else:
      if maNC < notas[l,c]:
        maNC = notas[l,c]
      if maNS < notas[l,c]:
        maNS = notas[l,c]
  print('\nA maior nota do {}º módulo é {}.' .format(l+1,maNS),end="\n\n")
print('A maior nota do curso é', maNC)
print('\nOs seguintes alunos tiraram nota 2:')
for l in range(6):
  for c in range(35):
    if notas[l,c] == 2:
      print('O aluno nº {} do {}º módulo.' .format(c+1,l+1))

In [0]:
# ALTERNATIVO 6. Criar uma matriz para os 6 módulos com 35 alunos
import numpy as np
notas = np.array([[ 2,  9,  2,  8,  7,  5,  3,  6,  9,  7,  4,  8,  2,  0,  6,  3,
         9,  2,  1,  9,  7, 8,  9,  3,  7,  1,  0, 6,  7,  6,  6,  4,
        9,  5,  4],
       [ 4,  1,  4,  3, 10,  1,  0,  4,  1,  4,  7,  4, 10,  0,  7,  2,
         0,  2,  1,  2,  0,  2,  8,  4,  5,  2, 10,  9,  1,  8,  9,  4,
         0, 10,  8],
       [ 3, 10,  9,  2,  1,  9,  3,  4,  4,  9,  7,  4,  4,  6, 10,  8,
         8,  2,  5,  1,  8,  0,  0,  1,  5,  7,  3,  9,  7,  4, 10,  5,
         8,  5,  7],
       [ 2,  0,  4,  8,  2,  4,  3,  0,  8,  4,  5,  1,  3,  4,  7,  9,
         1,  8,  3,  8,  0,  0,  4,  8,  6,  5,  9,  0, 2,  3,  7,  3,
         2,  2,  3],
       [ 6,  3,  0,  7,  7,  7,  4,  1,  7,  1,  2,  8,  9,  8,  4,  9,
         6,  6,  4,  0,  7,  3, 10,  9,  3,  7, 10,  1,  8,  7,  0,  9,
         2,  6, 10],
       [10,  5, 10, 10,  4,  6,  8,  9,  6, 10,  8,  2,  9,  8,  3,  2,
         8,  9,  1,  6,  3,  5, 10,  2, 10,  5,  6,  0,  0,  8,  4,  4,
         9, 10,  6]])
for l in range(6):
  maNS = -1
  for c in range(35):
    if l == 0 and c == 0:
      maNC = notas[l,c]
      maNS = notas[l,c]
    else:
      if maNC < notas[l,c]:
        maNC = notas[l,c]
      if maNS < notas[l,c]:
        maNS = notas[l,c]
  print('A maior nota do {}º módulo é {}.' .format(l+1,maNS),end="\n")
print('\nA maior nota do curso é', maNC)
print('\nOs seguintes alunos tiraram nota 2:')
for l in range(6):
  for c in range(35):
    if notas[l,c] == 2:
      print('O aluno nº {} do {}º módulo.' .format(c+1,l+1))

A maior nota do 1º módulo é 9.
A maior nota do 2º módulo é 10.
A maior nota do 3º módulo é 10.
A maior nota do 4º módulo é 9.
A maior nota do 5º módulo é 10.
A maior nota do 6º módulo é 10.

A maior nota do curso é 10

Os seguintes alunos tiraram nota 2:
O aluno nº 1 do 1º módulo.
O aluno nº 3 do 1º módulo.
O aluno nº 13 do 1º módulo.
O aluno nº 18 do 1º módulo.
O aluno nº 16 do 2º módulo.
O aluno nº 18 do 2º módulo.
O aluno nº 20 do 2º módulo.
O aluno nº 22 do 2º módulo.
O aluno nº 26 do 2º módulo.
O aluno nº 4 do 3º módulo.
O aluno nº 18 do 3º módulo.
O aluno nº 1 do 4º módulo.
O aluno nº 5 do 4º módulo.
O aluno nº 29 do 4º módulo.
O aluno nº 33 do 4º módulo.
O aluno nº 34 do 4º módulo.
O aluno nº 11 do 5º módulo.
O aluno nº 33 do 5º módulo.
O aluno nº 12 do 6º módulo.
O aluno nº 16 do 6º módulo.
O aluno nº 24 do 6º módulo.


In [0]:
#6. EXPLICADO Criar uma matriz para os 6 módulos com 35 alunos
import numpy as np
notas = np.empty([3,4])
for l in range(3):
  maNS = -1 #essa é a variável Maior Nota da Sala, que deve ser 'zerada' antes de iniciar o laço 
  for c in range(4):
    notas[l,c] = float(input('Informe a nota do {}º aluno do {}º módulo: ' .format(c+1,l+1)))
    if l == 0 and c == 0: # esse código atribui o valor da primeira nota como a maior delas
      maNC = notas[l,c] # variável Maior nota do Curso
      maNS = notas[l,c]# variável Maior nota da Sala
    else:
      if maNC < notas[l,c]: # testa se a nota incluída é maior do que a da variável Maior nota do Curso 
        maNC = notas[l,c] # se for Verdade, a nota incluída é atribuída à variável maNC
      if maNS < notas[l,c]: # testa se a nota incluída é maior do que a da variável Maior nota da Sala 
        maNS = notas[l,c] # se for Verdade, a nota incluída é atribuída à variável maNS
  print('\nA maior nota do {}º módulo é {}.' .format(l+1,maNS),end="\n\n") #imprime a maNS (da sala)
print('A maior nota do curso é', maNC) # depois de sair do laço das notas da sala ele imprime a maior do Curso
print('\nOs seguintes alunos tiraram nota 2:')
for l in range(3):
  for c in range(4):
    if notas[l,c] == 2: # testa se o aluno tirou nota 2
      print('O aluno nº {} do {}º módulo.' .format(c+1,l+1))

###7.Faça um programa que carregue uma matriz 2 x 2 int e encontre o maior elemento da matriz, crie uma matriz resultante que armazene e mostre o cálculo dos elementos da matriz original multiplicados pelo maior valor encontrado.


In [0]:
# 7.Faça um programa que carregue uma matriz 2 x 2 int
import numpy as np
mat = np.empty([2,2], dtype=int)
mat2 = np.empty([2,2], dtype=int)
for l in range(2):
  for c in range(2):
    mat[l,c] = int(input('Informe um número inteiro: '))
    if l == 0 and c == 0:
      maN = mat[l,c]
    else:
      if maN < mat[l,c]:
        maN = mat[l,c]
print()
for l in range(2):
  for c in range(2):
    mat2[l,c] = mat[l,c]*maN
    print('{} x {} = {}.' .format(mat[l,c],maN,mat2[l,c]))
print('\n A matriz multiplicada pelo maior número é: ', end='')
print(*mat2, sep=", ", end=".")

Informe um número inteiro: 10
Informe um número inteiro: 20
Informe um número inteiro: 40
Informe um número inteiro: 80

10 x 80 = 800.
20 x 80 = 1600.
40 x 80 = 3200.
80 x 80 = 6400.

 A matriz multiplicada pelo maior número é: [ 800 1600], [3200 6400].

###8. Faça um programa que a partir de uma matriz 4x4 mostre a soma dos elementos da diagonal principal. Mostre também  a soma dos elementos que estão acima da diagonal principal.


In [0]:
# 8. Faça um programa que a partir de uma matriz 4x4
import numpy as np
mat = np.empty([4,4], dtype=int)
sDiag = 0
sAcDiag = 0
for l in range(4):
  for c in range(4):
    mat[l,c] = int(input('Informe um número inteiro: '))
    if l == c:
      sDiag += mat[l,c]
    elif c > l:
      sAcDiag += mat[l,c]
print('\nA soma dos elementos da diagnonal principal é {}.' .format(sDiag))
print('A soma dos elementos ACIMA da diagnonal principal é {}.' .format(sAcDiag))


Informe um número inteiro: 1
Informe um número inteiro: 2
Informe um número inteiro: 3
Informe um número inteiro: 4
Informe um número inteiro: 5
Informe um número inteiro: 6
Informe um número inteiro: 7
Informe um número inteiro: 8
Informe um número inteiro: 9
Informe um número inteiro: 10
Informe um número inteiro: 11
Informe um número inteiro: 12
Informe um número inteiro: 13
Informe um número inteiro: 14
Informe um número inteiro: 15
Informe um número inteiro: 16

A soma dos elementos da diagnonal principal é 34.
A soma dos elementos ACIMA da diagnonal principal é 36.


In [0]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


###9. Faça um programa que carregue uma matriz 10 x 20 com números inteiros e some cada uma das linhas, armazenando o resultado das somas em um vetor. A seguir, multiplique cada elemento da matriz pela soma da linha e mostre a matriz resultante.


In [0]:
# 9. Faça um programa que carregue uma matriz 10 x 20
import numpy as np
mat = np.empty([3,4], dtype=int)
vet = []
for l in range(3):
  sLinha = 0
  for c in range(4):
    mat[l,c] = int(input('Informe um número inteiro: '))
    sLinha += mat[l,c]
  vet.append(sLinha)
for s in range(len(vet)):
  matR = mat * vet[s]
  print('\n',matR, end='\n')


Informe um número inteiro: 1
Informe um número inteiro: 1
Informe um número inteiro: 1
Informe um número inteiro: 1
Informe um número inteiro: 2
Informe um número inteiro: 2
Informe um número inteiro: 2
Informe um número inteiro: 2
Informe um número inteiro: 3
Informe um número inteiro: 3
Informe um número inteiro: 3
Informe um número inteiro: 3

 [[ 4  4  4  4]
 [ 8  8  8  8]
 [12 12 12 12]]

 [[ 8  8  8  8]
 [16 16 16 16]
 [24 24 24 24]]

 [[12 12 12 12]
 [24 24 24 24]
 [36 36 36 36]]


In [0]:
# 9. Faça um programa que carregue uma matriz 10 x 20
import numpy as np
mat = np.empty([10,20], dtype=int)
vet = []
for l in range(10):
  sLinha = 0
  for c in range(20):
    mat[l,c] = int(input('Informe um número inteiro: '))
    sLinha += mat[l,c]
  vet.append(sLinha)
for s in range(len(vet)):
  matR = mat * vet[s]
  print('\n',matR, end='\n')

In [0]:
# ALTERNATIVO 9. Faça um programa que carregue uma matriz 10 x 20
import numpy as np
mat = np.array([[ 76,  52,  65,  21,  42,  26,  92,  73,  76,  23,  80,  22,  79,
         47,  36,  72,  60,  22,  80,  56],
       [ 36,   3,  33,  65,  58,  72,  41,   1,  47,  18,  49,  43,  80,
         42,  47,  83,  37,  89,   4,  45],
       [ 11,   4,  80,  63,  59, 100,  12,  34,  11,  59,  60,  81,  73,
         60,  29,  41,  66,  43,  21,  33],
       [  4,  59,  59,  20,  99,  31,  70,  90,  32,  42,  35,  45,  74,
         13,  58,  95,  51,  24,   8,  45],
       [ 55,  28,  98,  43,  21,  53,  54,  12,  77,  42,  86,  23,  91,
         12,  29,  24,  73,  42,  85,  26],
       [100,  58,  78,  71,   5,  34,  80,  12,  71,  67,  61,  29,  22,
         61,  39,   9,  85,  54,  61,  48],
       [ 88,  15,  69,  68,  90,  76,  30,  50,   4,  17,  37,  70,  93,
         16,   5,  88,  23,  46,  28,  58],
       [ 80,   8,  10,  57,  94,  10,  14,  25,  35,  37,  19,  63,  73,
         78,  20,  67,   5,  48,  37,  30],
       [ 79,   7,  95,  66,  30,  34, 100,  52,  63,  80,  89,  13,  84,
         92,  21,  10,  81,  64,  80,  33],
       [ 32,  18,  82,  25,  42,  57,  22,  34,  74,  92,  24,  58,  49,
         34,  82,  43,  88,  61,   8,  49]])
vet = []
for l in range(10):
  sLinha = 0
  for c in range(20):
    sLinha += mat[l,c]
  vet.append(sLinha)
for s in range(len(vet)):
  matR = mat * vet[s]
  print('\n',matR, end='\n')


 [[ 83600  57200  71500  23100  46200  28600 101200  80300  83600  25300
   88000  24200  86900  51700  39600  79200  66000  24200  88000  61600]
 [ 39600   3300  36300  71500  63800  79200  45100   1100  51700  19800
   53900  47300  88000  46200  51700  91300  40700  97900   4400  49500]
 [ 12100   4400  88000  69300  64900 110000  13200  37400  12100  64900
   66000  89100  80300  66000  31900  45100  72600  47300  23100  36300]
 [  4400  64900  64900  22000 108900  34100  77000  99000  35200  46200
   38500  49500  81400  14300  63800 104500  56100  26400   8800  49500]
 [ 60500  30800 107800  47300  23100  58300  59400  13200  84700  46200
   94600  25300 100100  13200  31900  26400  80300  46200  93500  28600]
 [110000  63800  85800  78100   5500  37400  88000  13200  78100  73700
   67100  31900  24200  67100  42900   9900  93500  59400  67100  52800]
 [ 96800  16500  75900  74800  99000  83600  33000  55000   4400  18700
   40700  77000 102300  17600   5500  96800  25300  5060

###10. Faça um programa que carregue: *um vetor com oito posições com os nomes das lojas; * um outro vetor com quatro posições com os nomes dos produtos; * uma matriz com os preços de todos os produtos em cada loja. O programa deve mostrar todas as relações (nome do produto – nome da loja) nas quais o preço não ultrapasse R$ 100,00.


In [1]:
# 10. Faça um programa que carregue:
import numpy as np
nL = []
nPro = []
prePL = np.empty([3,2], dtype=float)
for lo in range(3):
  nL.append(input('Informe o nome da {}ª loja: ' .format(lo+1)))
print()
for pro in range(2):
  nPro.append(input('Informe o nome do {}º produto: ' .format(pro+1)))
print()
for l in range(len(nL)):
  for c in range(len(nPro)):
    prePL[l,c] = float(input("Informe o preço do produto '{}' da loja '{}': R$" .format(nPro[c],nL[l])))
  print()
for l in range(len(nL)):
  for c in range(len(nPro)):
    if prePL[l,c] < 100:
      print("O preço do produto '{}' da loja '{}' não ultrapassa R$100,00, custando R${:.02f}.".format(nPro[c],nL[l],prePL[l,c]))

Informe o nome da 1ª loja: Prudente
Informe o nome da 2ª loja: Bernardes
Informe o nome da 3ª loja: Epitácio

Informe o nome do 1º produto: Notebook
Informe o nome do 2º produto: Mouse

Informe o preço do produto 'Notebook' da loja 'Prudente': R$2500
Informe o preço do produto 'Mouse' da loja 'Prudente': R$50

Informe o preço do produto 'Notebook' da loja 'Bernardes': R$2300
Informe o preço do produto 'Mouse' da loja 'Bernardes': R$70

Informe o preço do produto 'Notebook' da loja 'Epitácio': R$3500
Informe o preço do produto 'Mouse' da loja 'Epitácio': R$65

O preço do produto 'Mouse' da loja 'Prudente' não ultrapassa R$100,00, custando R$50.00.
O preço do produto 'Mouse' da loja 'Bernardes' não ultrapassa R$100,00, custando R$70.00.
O preço do produto 'Mouse' da loja 'Epitácio' não ultrapassa R$100,00, custando R$65.00.


In [0]:
# 10. Faça um programa que carregue:
import numpy as np
nL = []
nPro = []
prePL = np.empty([8,4], dtype=float)
for lo in range(8):
  nL.append(input('Informe o nome da {}ª loja: ' .format(lo+1)))
print()
for pro in range(4):
  nPro.append(input('Informe o nome do {}º produto: ' .format(pro+1)))
print()
for l in range(len(nL)):
  for c in range(len(nPro)):
    prePL[l,c] = float(input("Informe o preço do produto '{}' da loja '{}': R$" .format(nPro[c],nL[l])))
  print()
for l in range(len(nL)):
  for c in range(len(nPro)):
    if prePL[l,c] < 100:
      print("O preço do produto '{}' da loja '{}' não ultrapassa R$100,00.".format(nPro[c],nL[l]))

**EXTRA** - Criador de matrix com números aletórios

In [0]:
import random
import numpy as np
mat = np.empty([10,20], dtype=int)
for s in range(10):
  for a in range(20):
			mat[s,a] = random.randint(1,100)
mat

array([[ 76,  52,  65,  21,  42,  26,  92,  73,  76,  23,  80,  22,  79,
         47,  36,  72,  60,  22,  80,  56],
       [ 36,   3,  33,  65,  58,  72,  41,   1,  47,  18,  49,  43,  80,
         42,  47,  83,  37,  89,   4,  45],
       [ 11,   4,  80,  63,  59, 100,  12,  34,  11,  59,  60,  81,  73,
         60,  29,  41,  66,  43,  21,  33],
       [  4,  59,  59,  20,  99,  31,  70,  90,  32,  42,  35,  45,  74,
         13,  58,  95,  51,  24,   8,  45],
       [ 55,  28,  98,  43,  21,  53,  54,  12,  77,  42,  86,  23,  91,
         12,  29,  24,  73,  42,  85,  26],
       [100,  58,  78,  71,   5,  34,  80,  12,  71,  67,  61,  29,  22,
         61,  39,   9,  85,  54,  61,  48],
       [ 88,  15,  69,  68,  90,  76,  30,  50,   4,  17,  37,  70,  93,
         16,   5,  88,  23,  46,  28,  58],
       [ 80,   8,  10,  57,  94,  10,  14,  25,  35,  37,  19,  63,  73,
         78,  20,  67,   5,  48,  37,  30],
       [ 79,   7,  95,  66,  30,  34, 100,  52,  63,  80,  89,  